const API='https://script.google.com/macros/s/AKfycbykjU1Oc2InJZ26__NJgjW0gK_scXvHkuuB8wU-pdCptURFxHCm030Q1Z3wJ9MqJ7A/exec';
const $=s=>document.querySelector(s); let duties=[];
async function api(p){const u=new URL(API);Object.entries(p).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u);if(!r.ok)throw Error();return r.json()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function fmt(d){let [y,m,x]=d.split("-").map(Number);return new Intl.DateTimeFormat("he-IL",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date(y,m-1,x))}
async function init(){try{let d=await api({action:"teachers"}),s=$("#teacher");s.innerHTML='<option value="">בחירת מורה</option>';d.teachers.forEach(t=>s.add(new Option(t,t)))}catch(e){$("#msg").textContent="לא ניתן לטעון את רשימת המורים."}}
$("#teacher").onchange=async e=>{let t=e.target.value;$("#add").disabled=true;if(!t)return;$("#duties").innerHTML='<div class="empty">טוען…</div>';try{let d=await api({action:"duties",teacher:t});duties=d.duties||[];$("#add").disabled=!duties.length;$("#duties").innerHTML=duties.length?duties.map(x=>`<article class="card"><div class="date">${fmt(x.date)}</div><div class="loc">${esc(x.location)}</div><div class="meta">${esc(x.week)} · 10:20 וגם 12:10</div></article>`).join(""):'<div class="empty">לא נמצאו תורנויות</div>'}catch(e){$("#msg").textContent="שגיאה בטעינת התורנויות."}};
function icsDate(date,time){return date.replaceAll("-","")+"T"+time.replace(":","")+"00"}
function clean(s){return String(s).replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;")}
function event(date,start,end,title,desc,alarmMin,uid){return `BEGIN:VEVENT\r\nUID:${uid}\r\nDTSTAMP:${new Date().toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z/,"Z")}\r\nDTSTART;TZID=Asia/Jerusalem:${icsDate(date,start)}\r\nDTEND;TZID=Asia/Jerusalem:${icsDate(date,end)}\r\nSUMMARY:${clean(title)}\r\nDESCRIPTION:${clean(desc)}\r\nBEGIN:VALARM\r\nTRIGGER:-PT${alarmMin}M\r\nACTION:DISPLAY\r\nDESCRIPTION:${clean(title)}\r\nEND:VALARM\r\nEND:VEVENT\r\n`}
$("#add").onclick=()=>{let teacher=$("#teacher").value,body="BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//School Duty//HE\r\nCALSCALE:GREGORIAN\r\nMETHOD:PUBLISH\r\nX-WR-CALNAME:תורנויות בית הספר\r\n";
duties.forEach((d,i)=>{let base=`${d.date}-${i}-${encodeURIComponent(teacher)}@school-duty`;body+=event(d.date,"08:00","08:05","היום יש לך תורנות",`מיקום: ${d.location}` ,0,base+"-morning");body+=event(d.date,"10:20","10:35",`תורנות – ${d.location}`,"הפסקה קטנה",10,base+"-small");body+=event(d.date,"12:10","12:35",`תורנות – ${d.location}`,"הפסקה גדולה",10,base+"-large")});body+="END:VCALENDAR\r\n";
let blob=new Blob([body],{type:"text/calendar;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`תורנויות-${teacher}.ics`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$("#msg").textContent="הקובץ מוכן. פתחו אותו ובחרו את היומן הקיים שאליו תרצו להוסיף את התורנויות."};
init();
